services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_ADDRESS=http://elasticsearch:9200
      - PORT=8080
      - FRONTEND_DIR=/app/frontend
    depends_on:
      elasticsearch:
        condition: service_healthy

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
